[package]
name = "rpgmad-lib"
version = "2.0.0"
authors = ["savannstm <savannstm@gmail.com>"]
edition = "2021"
rust-version = "1.60.0"
description = "Library for decrypting RPG Maker `rgss` archives."
readme = "README.md"
repository = "https://github.com/savannstm/rpgm-archive-decrypter-lib"
documentation = "https://docs.rs/rpgmad-lib"
license-file = "LICENSE.md"

[dependencies]
thiserror = "1.0.65"

[dev-dependencies]
marshal-rs = "0.4.0"
png = "0.17.16"
