[package]
name = "rpgmard-wasm"
version = "0.1.0"
authors = ["savannstm <savannstm@gmail.com>"]
edition = "2021"
rust-version = "1.71.0"
description = "WASM bindings for rpgmad-lib."
repository = "https://github.com/RPG-Maker-Translation-Tools/rpgm-archive-decrypter-lib"
documentation = "https://github.com/RPG-Maker-Translation-Tools/rpgm-archive-decrypter-lib/tree/master/crates/rpgmard-wasm"
license-file = "LICENSE.md"
keywords = ["rpgmaker", "rgss", "wasm", "decrypt", "encrypt"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rpgmad-lib = { path = "../.." }
wasm-bindgen = "=0.2.127"
