[package]
name = "rpgmard-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "WASM bindings for rpgmad-lib."
repository = "https://github.com/RPG-Maker-Translation-Tools/rpgm-archive-decrypter-lib"
documentation = "https://github.com/RPG-Maker-Translation-Tools/rpgm-archive-decrypter-lib/tree/master/crates/rpgmard-wasm"
license-file = "LICENSE.md"
keywords = ["rpgmaker", "rgss", "wasm", "decrypt", "encrypt"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
rpgmad-lib = { path = "../.." }
wasm-bindgen = "=0.2.127"
